### ISSUE TITLE
ActiveLDAP is not working with Ruby 2.2.0

### ISSUE THREAD

**Issue by kallak** [activeldap/activeldap#115]
I Tested ActiveLDAP with Ruby 2.2.0 using Travis CI.

Here is the failing result:
https://travis-ci.org/kallak/activeldap/jobs/47899147

```text
Error: test_find_operational_attributes(TestFind)
: ArgumentError: wrong number of arguments (9 for 10)
/home/travis/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/time.rb:250:in `make_time'
/home/travis/build/kallak/activeldap/lib/active_ldap/schema/syntaxes.rb:195:in `type_cast'
/home/travis/build/kallak/activeldap/lib/active_ldap/schema.rb:358:in `type_cast'
/home/travis/build/kallak/activeldap/lib/active_ldap/schema.rb:545:in `send_to_syntax'
/home/travis/build/kallak/activeldap/lib/active_ldap/schema.rb:482:in `type_cast'
/home/travis/build/kallak/activeldap/lib/active_ldap/attribute_methods/read.rb:38:in `type_cast'
/home/travis/build/kallak/activeldap/lib/active_ldap/attribute_methods/read.rb:18:in `get_attribute'
/home/travis/build/kallak/activeldap/lib/active_ldap/attribute_methods/read.rb:8:in `attribute'
/home/travis/.rvm/gems/ruby-2.2.0/gems/activemodel-4.2.0/lib/active_model/attribute_methods.rb:442:in `attribute_missing'
/home/travis/.rvm/gems/ruby-2.2.0/gems/activemodel-4.2.0/lib/active_model/attribute_methods.rb:433:in `method_missing'
...
```

**Comment by kou** [comment]
Thanks for your report!
I've fixed the problem at master. But there are other problems.
