### ISSUE TITLE
Map on alias seems doesn't work

### ISSUE THREAD

**Issue by bleuchtang** [activeldap/activeldap#121]
Hi,
I try to map alias with activeldap but it seems doesn't work. This is simple use case to reproduce the bug:

alias in ldap:
```
dn: cn=devops,ou=groups,dc=example,dc=net
cn: devops
aliasedObjectName: cn=ops,ou=groups,dc=example,dc=net
objectClass: alias
objectClass: extensibleObject
```

test.rb:
```ruby
#!/usr/bin/env ruby                                                                 
                                                                                
base = File.expand_path(File.join(File.dirname(__FILE__)))                      
$LOAD_PATH << File.join(base)                                                   
                                                                                
require 'active_ldap'                                                           
require 'objects/user'                                                          
require 'objects/group_alias'                                                   
require 'objects/group' 
ActiveLdap::Base.setup_connection(...)

g='devops'                                                                      
unless GroupAlias.exists?(g)                                                    
  $stderr.puts("Group #{g} doesn't exist")                                      
  exit 1                                                                        
end  
group = GroupAlias.find(g)                                                   
puts group.dn                                                                      
```

objects/group_alias.rb:
```ruby
class GroupAlias < ActiveLdap::Base
  ldap_mapping :prefix => 'ou=groups',
    :classes => ['alias', 'extensibleObject']
  has_many :alias, :class_name => "Group",
    :wrap => 'aliasedObjectName',
    :primary_key => 'dn'
end # Group   
```

The error is:
```
/home/emile/.gem/ruby/2.1.0/gems/activeldap-4.0.4/lib/active_ldap/attribute_methods/write.rb:30:in `set_attribute': cn is unknown attribute (ActiveLdap::UnknownAttribute)
	from /home/emile/.gem/ruby/2.1.0/gems/activeldap-4.0.4/lib/active_ldap/attribute_methods/dirty.rb:39:in `set_attribute'
	from /home/emile/.gem/ruby/2.1.0/gems/activeldap-4.0.4/lib/active_ldap/base.rb:774:in `dn='
	from /home/emile/.gem/ruby/2.1.0/gems/activeldap-4.0.4/lib/active_ldap/base.rb:1078:in `initialize_by_ldap_data'
	from /home/emile/.gem/ruby/2.1.0/gems/activeldap-4.0.4/lib/active_ldap/base.rb:609:in `block in instantiate'
	from /home/emile/.gem/ruby/2.1.0/gems/activeldap-4.0.4/lib/active_ldap/base.rb:608:in `instance_eval'
	from /home/emile/.gem/ruby/2.1.0/gems/activeldap-4.0.4/lib/active_ldap/base.rb:608:in `instantiate'
	from /home/emile/.gem/ruby/2.1.0/gems/activeldap-4.0.4/lib/active_ldap/callbacks.rb:38:in `instantiate_with_callbacks'
	from /home/emile/.gem/ruby/2.1.0/gems/activeldap-4.0.4/lib/active_ldap/operations.rb:295:in `block in find_every'
	from /home/emile/.gem/ruby/2.1.0/gems/activeldap-4.0.4/lib/active_ldap/operations.rb:294:in `collect'
	from /home/emile/.gem/ruby/2.1.0/gems/activeldap-4.0.4/lib/active_ldap/operations.rb:294:in `find_every'
	from /home/emile/.gem/ruby/2.1.0/gems/activeldap-4.0.4/lib/active_ldap/operations.rb:266:in `find_initial'
	from /home/emile/.gem/ruby/2.1.0/gems/activeldap-4.0.4/lib/active_ldap/operations.rb:335:in `find_one'
	from /home/emile/.gem/ruby/2.1.0/gems/activeldap-4.0.4/lib/active_ldap/operations.rb:322:in `find_from_dns'
	from /home/emile/.gem/ruby/2.1.0/gems/activeldap-4.0.4/lib/active_ldap/operations.rb:239:in `find'
	from test.rb:30:in `<main>'
```

As I understand, cn is not know because nether alias or extensibleObject objectClass require it so activeldap doesn't take it, but the organizationnalUnit (objectClass on ou=groups,dc=example,dc=net) on my ldap require it. Maybe it's not a bug but just an wrong configuration on my side...

Thanks.

**Comment by kou** [comment]
How about adding `organizationalRole` `objectClass` to the entry? `organizationalRole` requires `cn`.

**Comment by bleuchtang** [comment]
An object class violation is raised after adding organizationalRole to the entry.

**Comment by kou** [comment]
Do you know why an object class violation is raised?

**Comment by bleuchtang** [comment]
Because organizationalRole  does not inherit of alias.

Error When I add organizationalRole:
    ldap_modify: Object class violation (65)
	    additional info: invalid structural object class chain (alias/organizationalRole)

The only way to add cn is to add extensibleObject objectClass but in this case activeLdap can't know all required attributes.
