### ISSUE TITLE
Loading schema with JNDI paged searching throws UnavailableCriticalExtension on OpenDJ

### ISSUE THREAD

**Issue by HarlemSquirrel** [activeldap/activeldap#172]
```
Loading test environment (Rails 4.2.11.1)
irb: warn: can't alias context from irb_context.
jruby-9.2.11.0 :001 > Person.schema
Attempting to reconnect
  LDAP: connect (1.0ms) {:uri=>"ldap://localhost:13891", :with_start_tls=>false}
  LDAP: bind (117.7ms) {:dn=>"<REDACTED>"}
Bound to ldap://localhost:13891 by simple as <REDACTED>
  LDAP: search (82.0ms) {:base=>"", :scope=>:base, :filter=>"objectClass=*", :attributes=>["subschemaSubentry"], :limit=>1, :use_paged_results=>false, :page_size=>500}
  LDAP: search (5.7ms) {:base=>"", :scope=>:base, :filter=>"objectClass=*", :attributes=>["supportedControl"], :limit=>1, :use_paged_results=>false, :page_size=>500}
  LDAP: search (44.5ms) {:base=>"cn=schema", :scope=>:base, :filter=>"(objectClass=subschema)", :attributes=>["objectClasses", "attributeTypes", "matchingRules", "matchingRuleUse", "dITStructureRules", "dITContentRules", "nameForms", "ldapSyntaxes"], :limit=>1, :use_paged_results=>true, :page_size=>500}
Traceback (most recent call last):
       16: from org/jruby/ext/timeout/Timeout.java:76:in `timeout'
       15: from org/jruby/ext/timeout/Timeout.java:90:in `timeout'
       14: from org/jruby/ext/timeout/Timeout.java:97:in `timeout'
       13: from /home/kem2028/.rvm/gems/jruby-9.2.11.0/gems/activeldap-6.0.0/lib/active_ldap/adapter/base.rb:308:in `block in operation'
       12: from /home/kem2028/.rvm/gems/jruby-9.2.11.0/gems/activeldap-6.0.0/lib/active_ldap/adapter/base.rb:150:in `block in schema'
       11: from /home/kem2028/.rvm/gems/jruby-9.2.11.0/gems/activeldap-6.0.0/lib/active_ldap/adapter/jndi.rb:49:in `search'
       10: from /home/kem2028/.rvm/gems/jruby-9.2.11.0/gems/activeldap-6.0.0/lib/active_ldap/adapter/base.rb:197:in `search'
        9: from /home/kem2028/.rvm/gems/jruby-9.2.11.0/gems/activeldap-6.0.0/lib/active_ldap/adapter/base.rb:307:in `operation'
        8: from /home/kem2028/.rvm/gems/jruby-9.2.11.0/gems/activeldap-6.0.0/lib/active_ldap/adapter/base.rb:354:in `with_timeout'
        7: from org/jruby/ext/timeout/Timeout.java:76:in `timeout'
        6: from org/jruby/ext/timeout/Timeout.java:90:in `timeout'
        5: from org/jruby/ext/timeout/Timeout.java:97:in `timeout'
        4: from /home/kem2028/.rvm/gems/jruby-9.2.11.0/gems/activeldap-6.0.0/lib/active_ldap/adapter/base.rb:308:in `block in operation'
        3: from /home/kem2028/.rvm/gems/jruby-9.2.11.0/gems/activeldap-6.0.0/lib/active_ldap/adapter/base.rb:198:in `block in search'
        2: from /home/kem2028/.rvm/gems/jruby-9.2.11.0/gems/activeldap-6.0.0/lib/active_ldap/adapter/jndi.rb:52:in `block in search'
        1: from /home/kem2028/.rvm/gems/jruby-9.2.11.0/gems/activeldap-6.0.0/lib/active_ldap/adapter/jndi.rb:103:in `execute'
ActiveLdap::LdapError::UnavailableCriticalExtension (The search request cannot be processed because it contains a critical control with OID 1.2.840.113556.1.4.319 that is not supported by the Directory Server for this type of operation)
```

**Comment by kou** [comment]
Does the following solve this?

```diff
diff --git a/lib/active_ldap/adapter/base.rb b/lib/active_ldap/adapter/base.rb
index d403edf..dcc2813 100644
--- a/lib/active_ldap/adapter/base.rb
+++ b/lib/active_ldap/adapter/base.rb
@@ -151,7 +151,8 @@ module ActiveLdap
                  :scope => :base,
                  :filter => '(objectClass=subschema)',
                  :attributes => attrs,
-                 :limit => 1) do |dn, attributes|
+                 :limit => 1,
+                 :use_paged_results => false) do |dn, attributes|
             schema = Schema.new(attributes)
           end
           schema || Schema.new([])
```

**Comment by HarlemSquirrel** [comment]
@kou that does fix the issue but it might be nice to disable paged seach when the limit is 1 for any search
